# Generated by Django 3.2.5 on 2021-11-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.TextField(default=None, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
