# Generated by Django 3.2.5 on 2021-11-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalincome',
            name='sales',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
