# Generated by Django 3.2.5 on 2021-11-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_totalincome_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveincome',
            name='archive_increase',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
