# Generated by Django 3.2.5 on 2021-11-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_archiveincome_archive_increase'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveincome',
            name='archive_income_increase',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
